### PR TITLE
Contest and user profile pages  v2.1 (dev)

### PR DESCRIPTION
**Pull request by jashandeep31**
### Major changes 
- Contests page 
- Create and manage contests (Admin can create contest from their admin page)
- Manage user profile page
- New design of problems page 

### Minor or other changes
- Changed/fixed the Prisma of the web app 
- Fixed auth system 
- New footer

Temp live link: http://134.209.157.134:3000/
may go down (I just tried to help with the working demo)

email : 123ghatrora123@gmail.com
password: QSu*u!&gylY!GVB*zm

Use these to admin login if its live

### CODE REVIEW

**Comment by hkirat** [comment]
@devsargam

**Comment by devsargam** [comment]
On it @hkirat

**Comment by jashandeep31** [comment]
@devsargam  live link and creds are added use those if you want :)       _(refer to description)_
Let me know if there are any Issues,

**Review by devsargam — APPROVED** [review]

**Comment by devsargam** [comment]
@jashandeep31 thank u so much sir. This repo was very hard to setup and u did all this 🥳

**Comment by jashandeep31** [comment]
> @jashandeep31 thank u so much sir. This repo was very hard to setup and u did all this 🥳

Thanks, Sir ♡

**Pull request merged**
