### PR TITLE
Fet/#41 k8s hpa using redis queue length

### PR DESCRIPTION
**Pull request by DipakKhade**
added a manidest for  horizontal pod autoscaling in the basis of redis queue length

### CODE REVIEW

**Comment by SujithThirumalaisamy** [comment]
Have you tested this in local or anywhere else?
I think you still dont get the current architechture we are in

**Comment by siinghd** [comment]
@DipakKhade is this straight gpt copy paste or u have tested anything written in it?

**Comment by DipakKhade** [comment]
i did'nt have a resources to test that , but i reviewed each and every line , and its config yml file no one write it from scratch witout ai or google it , i had googled many things and not just straight gpt copy paste and ya also some things are form gpt , there is no lie

**Comment by SujithThirumalaisamy** [comment]
> i did'nt have a resources to test that , but i reviewed each and every line , and its config yml file no one write it from scratch witout ai or google it , i had googled many things and not just straight gpt copy paste and ya also some things are form gpt , there is no lie

Yeah. But you dont follow the current architechture. Sure this is an issue. I already commented on you old PR.

**Comment by hkirat** [comment]
Closing this. PRs need to be tested before being created

**Pull request closed without merging**
