### PR TITLE
docker setup for web and submissions-webhook

### LINKED ISSUE #20: create a docker_setup to run the project locally
docker setup, with running apps/web and apps/submission-webhook together with db running locally

### PR DESCRIPTION
**Pull request by Ankur1493**
## Docker setup

Fixed #20 

This is a docker file and docker compose file to run the web and submissions-webhook simultaneously, along with the postgress database running on docker

image

image

### CODE REVIEW

**Comment by hkirat** [comment]
merging this but we need judge0 here as well

**Comment by SujithThirumalaisamy** [comment]
> merging this but we need judge0 here as well

Feels like making it too much resource intensive in local. But mandatory if we centralize the DB. But some people may struggle in dev.

**Comment by SujithThirumalaisamy** [comment]
@Ankur1493 Need a help from you can you please drop your discord?

**Comment by Ankur1493** [comment]
ankur3419

**Pull request merged**
